//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AminWebEntities : DbContext
    {
        public AminWebEntities()
            : base("name=AminWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblChat> TblChat { get; set; }
        public virtual DbSet<TblDocs> TblDocs { get; set; }
        public virtual DbSet<TblPlaylist> TblPlaylist { get; set; }
        public virtual DbSet<TblRole> TblRole { get; set; }
        public virtual DbSet<TblUser> TblUser { get; set; }
        public virtual DbSet<TblUserPlaylistRel> TblUserPlaylistRel { get; set; }
        public virtual DbSet<TblUserVideoRel> TblUserVideoRel { get; set; }
        public virtual DbSet<TblVideo> TblVideo { get; set; }
        public virtual DbSet<TblVideoPlaylistKeyword> TblVideoPlaylistKeyword { get; set; }
        public virtual DbSet<TblWithdraw> TblWithdraw { get; set; }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
