//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblConfig
    {
        public int ConfigId { get; set; }
        public Nullable<short> DarsadeSud { get; set; }
        public Nullable<int> SaqfeBardasht { get; set; }
        public string AboutUsBody { get; set; }
        public string Rules { get; set; }
    }
}
