//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTicket
    {
        public int TicketId { get; set; }
        public int SenderId { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string AttachmentUrl { get; set; }
        public System.DateTime DateSent { get; set; }
    
        public virtual TblUser TblUser { get; set; }
    }
}
