//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblUser()
        {
            this.TblChat = new HashSet<TblChat>();
            this.TblChat1 = new HashSet<TblChat>();
            this.TblLog = new HashSet<TblLog>();
            this.TblPlaylist = new HashSet<TblPlaylist>();
            this.TblTicket = new HashSet<TblTicket>();
            this.TblUserPlaylistRel = new HashSet<TblUserPlaylistRel>();
            this.TblUserVideoRel = new HashSet<TblUserVideoRel>();
            this.TblWithdraw = new HashSet<TblWithdraw>();
            this.TblVideo = new HashSet<TblVideo>();
        }
    
        public int UserId { get; set; }
        public string Name { get; set; }
        public string TellNo { get; set; }
        public string Email { get; set; }
        public int Balance { get; set; }
        public string Auth { get; set; }
        public bool IsActive { get; set; }
        public string Password { get; set; }
        public Nullable<int> DocsId { get; set; }
        public int RoleId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblChat> TblChat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblChat> TblChat1 { get; set; }
        public virtual TblDoc TblDoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblLog> TblLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblPlaylist> TblPlaylist { get; set; }
        public virtual TblRole TblRole { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblTicket> TblTicket { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUserPlaylistRel> TblUserPlaylistRel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUserVideoRel> TblUserVideoRel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblWithdraw> TblWithdraw { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVideo> TblVideo { get; set; }
    }
}
