//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using DataLayer.MetaData;
    
    
    [MetadataType(typeof(MdTblVideo))]
    public partial class TblVideo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblVideo()
        {
            this.TblUserVideoRel = new HashSet<TblUserVideoRel>();
            this.TblVideoPlaylistKeyword = new HashSet<TblVideoPlaylistKeyword>();
        }
    
        public int VideoId { get; set; }
        public string VideoUrl { get; set; }
        public string VidioDemoUrl { get; set; }
        public string MainImage { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string DateSubmited { get; set; }
        public int ViewCount { get; set; }
        public bool IsHome { get; set; }
        public int LikeCount { get; set; }
        public string Link { get; set; }
        public int UserId { get; set; }
        public int Price { get; set; }
        public bool IsCharity { get; set; }
        public Nullable<int> PlaylistId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual TblPlaylist TblPlaylist { get; set; }
        public virtual TblUser TblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblUserVideoRel> TblUserVideoRel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVideoPlaylistKeyword> TblVideoPlaylistKeyword { get; set; }
    }
}
