//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using DataLayer.MetaData;
    
    
    [MetadataType(typeof(MdTblWithdraw))]
    public partial class TblWithdraw
    {
        public int WithdrawId { get; set; }
        public int UserId { get; set; }
        public int Value { get; set; }
        public bool IsDone { get; set; }
        public string Description { get; set; }
    
        public virtual TblUser TblUser { get; set; }
    }
}
